document.addEventListener('DOMContentLoaded', () => {
    const tabs = document.querySelectorAll('.tab-btn');
    const barcodeFormatContainer = document.getElementById('barcodeFormatContainer');
    const inputData = document.getElementById('inputData');
    const generateBtn = document.getElementById('generateBtn');
    const outputSection = document.getElementById('outputSection');
    const qrcodeDisplay = document.getElementById('qrcodeDisplay');
    const barcodeDisplay = document.getElementById('barcodeDisplay');
    const downloadBtn = document.getElementById('downloadBtn');
    const barcodeFormat = document.getElementById('barcodeFormat');
    const colorSwatches = document.querySelectorAll('.color-swatch');

    let currentMode = 'qrcode'; // 'qrcode' or 'barcode'
    let currentColor = '#f97316'; // Default Orange
    let qrCodeInstance = null;

    // Color Selection
    colorSwatches.forEach(swatch => {
        swatch.addEventListener('click', () => {
            // Update Active Class
            colorSwatches.forEach(s => s.classList.remove('active'));
            swatch.classList.add('active');
            
            currentColor = swatch.dataset.color;
            
            // Auto regenerate if there's text
            if (inputData.value.trim()) {
                generateBtn.click();
            }
        });
    });

    // Tab Switching
    tabs.forEach(tab => {
        tab.addEventListener('click', () => {
            // Update Active Class
            tabs.forEach(t => t.classList.remove('active'));
            tab.classList.add('active');

            currentMode = tab.dataset.target;

            // Toggle Barcode format options
            if (currentMode === 'barcode') {
                barcodeFormatContainer.classList.remove('hidden');
                inputData.placeholder = "รหัสบาร์โค้ด เช่น 123456789";
            } else {
                barcodeFormatContainer.classList.add('hidden');
                inputData.placeholder = "ตัวอย่าง: https://www.google.com หรือ รหัสพัสดุ 123456789";
            }
            
            // Hide output when switching modes
            outputSection.classList.add('hidden');
        });
    });

    // Generate Code
    generateBtn.addEventListener('click', () => {
        const text = inputData.value.trim();
        if (!text) {
            alert('กรุณากรอกข้อมูลก่อนสร้างรหัส');
            return;
        }

        outputSection.classList.remove('hidden');

        if (currentMode === 'qrcode') {
            generateQRCode(text);
        } else {
            generateBarcode(text);
        }
    });

    function generateQRCode(text) {
        qrcodeDisplay.classList.remove('hidden');
        barcodeDisplay.classList.add('hidden');
        
        // Clear previous
        qrcodeDisplay.innerHTML = '';
        
        // Create new QR Code. Use high resolution (e.g. 512x512)
        // Note: qrcode.js draws to a canvas and an img tag
        qrCodeInstance = new QRCode(qrcodeDisplay, {
            text: text,
            width: 512,
            height: 512,
            colorDark : currentColor,
            colorLight : "#ffffff",
            correctLevel : QRCode.CorrectLevel.H
        });
        
        // Scale it down via CSS for display, but keep actual size large for downloading
        setTimeout(() => {
            const img = qrcodeDisplay.querySelector('img');
            const canvas = qrcodeDisplay.querySelector('canvas');
            if (img) {
                 img.style.maxWidth = '100%';
                 img.style.height = 'auto';
            }
            if (canvas) {
                 canvas.style.maxWidth = '100%';
                 canvas.style.height = 'auto';
            }
        }, 50);
    }

    function generateBarcode(text) {
        barcodeDisplay.classList.remove('hidden');
        qrcodeDisplay.classList.add('hidden');

        const format = barcodeFormat.value;
        
        try {
            JsBarcode("#barcodeDisplay", text, {
                format: format,
                width: 4,      // Thicker bars for high res
                height: 150,   // Taller bars
                displayValue: true,
                fontSize: 24,
                margin: 20,
                lineColor: currentColor
            });
            // Ensure it fits container visually
            barcodeDisplay.style.maxWidth = '100%';
            barcodeDisplay.style.height = 'auto';
        } catch (error) {
            alert('รูปแบบข้อมูลไม่ถูกต้องสำหรับฟอร์แมต ' + format + '\n\n' + error.message);
            outputSection.classList.add('hidden');
        }
    }

    // Download Image
    downloadBtn.addEventListener('click', () => {
        let downloadLink = document.createElement('a');
        let filename = currentMode === 'qrcode' ? `qrcode_${Date.now()}.png` : `barcode_${Date.now()}.png`;
        downloadLink.download = filename;

        if (currentMode === 'qrcode') {
            // Find the canvas generated by qrcode.js inside the display area
            const canvas = qrcodeDisplay.querySelector('canvas');
            const img = qrcodeDisplay.querySelector('img');
            
            if (canvas && canvas.style.display !== 'none') {
                 downloadLink.href = canvas.toDataURL("image/png");
                 downloadLink.click();
            } else if (img && img.src) {
                 downloadLink.href = img.src;
                 downloadLink.click();
            } else {
                 alert('ไม่สามารถดาวน์โหลดภาพได้');
            }
        } else {
            // Barcode uses the canvas directly
            if (barcodeDisplay) {
                downloadLink.href = barcodeDisplay.toDataURL("image/png");
                downloadLink.click();
            }
        }
    });
});
